---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Demo dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Server"
    icon: "fas fa-cloud"
    items:
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: ""
        tag: "app"
        keywords: ""
        url: "https://192.168.0.104:"
        target: "_blank"

      - name: "cli"
        logo: "assets/tools/cli.png"
        subtitle: ""
        tag: "app"
        keywords: ""
        url: "https://192.168.0.104:8902"
        target: "_blank"

  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: ""
        tag: "app"
        keywords: ""
        url: "https://192.168.0.104:8096"
        target: "_blank"

      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        subtitle: ""
        tag: "app"
        keywords: ""
        url: "https://192.168.0.104:8989"
        target: "_blank"

      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: ""
        tag: "app"
        keywords: ""
        url: "https://192.168.0.104:7878"
        target: "_blank"

      - name: "qBittorent"
        logo: "assets/tools/qbittorent.png"
        subtitle: ""
        tag: "app"
        keywords: ""
        url: "https://192.168.0.104:8080"
        target: "_blank"

      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.png"
        subtitle: ""
        tag: "app"
        keywords: ""
        url: "https://192.168.0.104:9696"
        target: "_blank"
